namespace GhostServiceBuster.IntegrationTests.Testees;

internal interface IServiceResolvedByServiceProvider;

internal sealed class ServiceResolvedByServiceProvider : IServiceResolvedByServiceProvider;