namespace GhostServiceBuster.IntegrationTests.Testees;

public interface IServiceInjectedIntoEndpointFilter;

internal sealed class ServiceInjectedIntoEndpointFilter: IServiceInjectedIntoEndpointFilter;