namespace GhostServiceBuster.IntegrationTests.Testees;

public interface IServiceInjectedIntoMinimalApiLambdaFromBody;

internal sealed class ServiceInjectedIntoMinimalApiLambdaFromBody: IServiceInjectedIntoMinimalApiLambdaFromBody;