namespace GhostServiceBuster.IntegrationTests.Testees;

public interface IServiceInjectedIntoMinimalApiLambda;

internal sealed class ServiceInjectedIntoMinimalApiLambda: IServiceInjectedIntoMinimalApiLambda;