namespace GhostServiceBuster.IntegrationTests.Testees;

public interface IServiceInjectedIntoMinimalApiHandler;

internal sealed class ServiceInjectedIntoMinimalApiHandler : IServiceInjectedIntoMinimalApiHandler;